project:
  type: book
  output-dir: docs

book:
  title: "MATH 321 --<br>Mathematical Statistics"
  author: "Colton Gearhart"
  date: last-modified
  cover-image: mathematical-statistics.png
  chapters:
    - index.qmd
    - syllabus.qmd

    - part: test-1.qmd
      chapters:
        - lecture-14.qmd
        - lecture-15.qmd
        - lecture-16.qmd
        - lecture-17.qmd
        - review-1.qmd

    - part: test-2.qmd
      chapters:
        - lecture-1.qmd
        - lecture-2.qmd
        - lecture-3.qmd
        - lecture-4.qmd
        - review-2.qmd

    - part: test-3.qmd
      chapters:
        - lecture-5.qmd
        - lecture-6.qmd
        - lecture-7.qmd
        - review-3.qmd

    - part: test-3-after.qmd
      chapters:
        - lecture-8.qmd
        - review-final.qmd

format:
  html:
    theme: flatly

title-block-banner: true
